### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/flexIRF#4]
When we looked at the code just now, one thing I found confusing was that symbols like `kAeff` are exposed by `#include "GIRF.h"`, e.g. here:
https://github.com/cta-observatory/flexIRF/blob/master/src/IRFsimpleReadIrf.cc#L49

I see it originates from here:
https://github.com/cta-observatory/flexIRF/blob/08d7708d7ec3fb8e86668c5857389777f5391de7/flexirf/include/GIRFPdf.h#L17

A good ways to expose an API from a C++ library is to put **everything** in a library top-level [namespace](http://en.cppreference.com/w/cpp/language/namespace).

Specifically for enums a better approach was introduced with `enum class` to have scoped enums:
http://en.cppreference.com/w/cpp/language/enum

(I know Gammalib only uses C++98, which doesn't support `enum class`, but as far as I know for the rest of the CTA software everyone is for using good, modern C++ and Python.)

**Comment by TarekHC** [comment]
> When we looked at the code just now, one thing I found confusing was that symbols like kAeff are exposed by #include "GIRF.h", e.g. here:
https://github.com/cta-observatory/flexIRF/blob/master/src/IRFsimpleReadIrf.cc#L49

> I see it originates from here:
https://github.com/cta-observatory/flexIRF/blob/08d7708d7ec3fb8e86668c5857389777f5391de7/flexirf/include/GIRFPdf.h#L17

Before, these enums were defined as public members of the parent classes, and it was much more elegant. In the whole mess of trying to wrap the code (a horrendous failure) I read somewhere that I had to change the enums definition as a class member, because it was not supported by swig (although I am not even sure if that's true). 

> A good ways to expose an API from a C++ library is to put everything in a library top-level namespace.

What does **everything** mean? All enums? Or even classes? I do have a namespace containing some useful methods (https://github.com/cta-observatory/flexIRF/blob/master/flexirf/include/GIRFUtils.h), although you probably refer to something including all public classes/methods of the repo? Do you have an example somewhere?

Thanks!

**Comment by cdeil** [comment]
I'm mostly a Python programmer.
There you have your imports at the top like:
```python
import numpy
import matplotlib.pyplot as plt
```
And in the code it's always clear from which package something came:
```python
a = numpy.sin(42)
plt.imshow(...)
```

In C / C++ you have an include at the top:
```
#include "fitsio.h"
#include "GIRFAxis.h"
```
and then, if you have many includes, if you read code like
```
	GIRFPdf* effArea = dynamic_cast<GIRFPdf*>(irf.ReadPdf(kAeff, config));
```
and you don't know where symbols (like `kAeff` in this case) came from.

So to make this simpler and to avoid name clashes for people that want to use several libraries,
it's good practice to put **everything** from your library in a namespace.
I.e. in your case:
```
namespace flexirf {
 // everything goes here
}
```

or to do what C libraries do, where no namespaces are available:
prefix **every** symbol from your library with a unique string like ``flexirf_`` or ``FlexIRF`` and achieve namespacing this way. This is what Gammalib does by using `G` ... there's a `GTime`, a `GEnergy`, ...
Example:
http://www.gnu.org/software/gsl/manual/html_node/QR-Decomposition.html#QR-Decomposition

I don't have much experience with SWIG ... so I don't know if SWIG wrappers really become harder if you introduce a namespace for your library.

**Comment by TarekHC** [comment]
Ok, I believe I implemented what you suggested here. You can check all examples now. Everything is inside the "flexIRF" namespace.

Although I dont like the name... It's probably non-standard at all...
